### Variables 
@apiurl = https://http://localhost:8000/

### GET users
GET https://http://localhost:8000/api/semestre
Content-Type: application/json

### POST users
###POST {{apiurl}}/users HTTP/1.1
###Content-Type: application/json
###Authorization: Bearer ACCESS-TOKEN

###{
   ###"name":"Tenali Ramakrishna",
   ###"gender":"Male",
   ###"email":"tenali.ramakrishna@15ce.com",
   ###"status":"Active"
###}

